version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: vidwa-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  server:
    build: .
    container_name: vidwa-server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://admin:password@mongodb:27017/vidwa-chat?authSource=admin
      - PORT=5000
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: vidwa-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev

volumes:
  mongodb_data:
