version: 2
build:
  commands:
    - echo "Installing dependencies..."
    - cd server && npm install
deploy:
  startCommand: cd server && npm start
  healthcheckPath: /
  healthcheckTimeout: 100s
  restartPolicyType: always
